# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui',
# licensing of 'design.ui' applies.
#
# Created: Fri Nov  1 17:27:36 2019
#      by: pyside2-uic  running on PySide2 5.13.2
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(281, 428)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(9, 9, 9, 9)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_1 = QtWidgets.QWidget()
        self.tab_1.setObjectName("tab_1")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab_1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.v_container = QtWidgets.QVBoxLayout()
        self.v_container.setObjectName("v_container")
        self.w_combo_run = QtWidgets.QWidget(self.tab_1)
        self.w_combo_run.setObjectName("w_combo_run")
        self.h_dropdown = QtWidgets.QHBoxLayout(self.w_combo_run)
        self.h_dropdown.setSpacing(6)
        self.h_dropdown.setContentsMargins(0, 0, 0, 0)
        self.h_dropdown.setObjectName("h_dropdown")
        self.combo_run = QtWidgets.QComboBox(self.w_combo_run)
        self.combo_run.setMinimumSize(QtCore.QSize(150, 0))
        self.combo_run.setObjectName("combo_run")
        self.combo_run.addItem("")
        self.combo_run.addItem("")
        self.combo_run.addItem("")
        self.combo_run.addItem("")
        self.combo_run.addItem("")
        self.h_dropdown.addWidget(self.combo_run)
        self.run_options = QtWidgets.QPushButton(self.w_combo_run)
        self.run_options.setObjectName("run_options")
        self.h_dropdown.addWidget(self.run_options)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.h_dropdown.addItem(spacerItem)
        self.v_container.addWidget(self.w_combo_run)
        self.w_window = QtWidgets.QWidget(self.tab_1)
        self.w_window.setObjectName("w_window")
        self.h_window = QtWidgets.QHBoxLayout(self.w_window)
        self.h_window.setContentsMargins(-1, 0, -1, 0)
        self.h_window.setObjectName("h_window")
        self.window_info_text = QtWidgets.QLabel(self.w_window)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.window_info_text.setPalette(palette)
        self.window_info_text.setObjectName("window_info_text")
        self.h_window.addWidget(self.window_info_text)
        self.window_retry = QtWidgets.QPushButton(self.w_window)
        self.window_retry.setObjectName("window_retry")
        self.h_window.addWidget(self.window_retry)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.h_window.addItem(spacerItem1)
        self.v_container.addWidget(self.w_window)
        self.w_elapsed = QtWidgets.QWidget(self.tab_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.w_elapsed.sizePolicy().hasHeightForWidth())
        self.w_elapsed.setSizePolicy(sizePolicy)
        self.w_elapsed.setObjectName("w_elapsed")
        self.h_elapsed = QtWidgets.QHBoxLayout(self.w_elapsed)
        self.h_elapsed.setSpacing(6)
        self.h_elapsed.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.h_elapsed.setContentsMargins(9, 0, 9, 0)
        self.h_elapsed.setObjectName("h_elapsed")
        self.elapsed_text = QtWidgets.QLabel(self.w_elapsed)
        self.elapsed_text.setObjectName("elapsed_text")
        self.h_elapsed.addWidget(self.elapsed_text)
        self.elapsed_data = QtWidgets.QLabel(self.w_elapsed)
        self.elapsed_data.setText("")
        self.elapsed_data.setObjectName("elapsed_data")
        self.h_elapsed.addWidget(self.elapsed_data)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.h_elapsed.addItem(spacerItem2)
        self.v_container.addWidget(self.w_elapsed)
        self.w_exp = QtWidgets.QWidget(self.tab_1)
        self.w_exp.setObjectName("w_exp")
        self.h_exp = QtWidgets.QHBoxLayout(self.w_exp)
        self.h_exp.setContentsMargins(-1, 0, -1, 0)
        self.h_exp.setObjectName("h_exp")
        self.exp_text = QtWidgets.QLabel(self.w_exp)
        self.exp_text.setObjectName("exp_text")
        self.h_exp.addWidget(self.exp_text)
        self.exp_data = QtWidgets.QLabel(self.w_exp)
        self.exp_data.setText("")
        self.exp_data.setObjectName("exp_data")
        self.h_exp.addWidget(self.exp_data)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.h_exp.addItem(spacerItem3)
        self.v_container.addWidget(self.w_exp)
        self.w_pp = QtWidgets.QWidget(self.tab_1)
        self.w_pp.setObjectName("w_pp")
        self.h_pp = QtWidgets.QHBoxLayout(self.w_pp)
        self.h_pp.setContentsMargins(-1, 0, -1, 0)
        self.h_pp.setObjectName("h_pp")
        self.pp_text = QtWidgets.QLabel(self.w_pp)
        self.pp_text.setObjectName("pp_text")
        self.h_pp.addWidget(self.pp_text)
        self.pp_data = QtWidgets.QLabel(self.w_pp)
        self.pp_data.setText("")
        self.pp_data.setObjectName("pp_data")
        self.h_pp.addWidget(self.pp_data)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.h_pp.addItem(spacerItem4)
        self.v_container.addWidget(self.w_pp)
        self.w_qp = QtWidgets.QWidget(self.tab_1)
        self.w_qp.setObjectName("w_qp")
        self.h_qp = QtWidgets.QHBoxLayout(self.w_qp)
        self.h_qp.setContentsMargins(-1, 0, -1, 0)
        self.h_qp.setObjectName("h_qp")
        self.qp_text = QtWidgets.QLabel(self.w_qp)
        self.qp_text.setObjectName("qp_text")
        self.h_qp.addWidget(self.qp_text)
        self.qp_data = QtWidgets.QLabel(self.w_qp)
        self.qp_data.setText("")
        self.qp_data.setObjectName("qp_data")
        self.h_qp.addWidget(self.qp_data)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.h_qp.addItem(spacerItem5)
        self.v_container.addWidget(self.w_qp)
        self.w_exph = QtWidgets.QWidget(self.tab_1)
        self.w_exph.setObjectName("w_exph")
        self.h_exph = QtWidgets.QHBoxLayout(self.w_exph)
        self.h_exph.setContentsMargins(-1, 0, -1, 0)
        self.h_exph.setObjectName("h_exph")
        self.exph_text = QtWidgets.QLabel(self.w_exph)
        self.exph_text.setObjectName("exph_text")
        self.h_exph.addWidget(self.exph_text)
        self.exph_data = QtWidgets.QLabel(self.w_exph)
        self.exph_data.setText("")
        self.exph_data.setObjectName("exph_data")
        self.h_exph.addWidget(self.exph_data)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.h_exph.addItem(spacerItem6)
        self.v_container.addWidget(self.w_exph)
        self.w_pph = QtWidgets.QWidget(self.tab_1)
        self.w_pph.setObjectName("w_pph")
        self.h_pph = QtWidgets.QHBoxLayout(self.w_pph)
        self.h_pph.setContentsMargins(-1, 0, -1, 0)
        self.h_pph.setObjectName("h_pph")
        self.pph_text = QtWidgets.QLabel(self.w_pph)
        self.pph_text.setObjectName("pph_text")
        self.h_pph.addWidget(self.pph_text)
        self.pph_data = QtWidgets.QLabel(self.w_pph)
        self.pph_data.setText("")
        self.pph_data.setObjectName("pph_data")
        self.h_pph.addWidget(self.pph_data)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.h_pph.addItem(spacerItem7)
        self.v_container.addWidget(self.w_pph)
        self.w_qph = QtWidgets.QWidget(self.tab_1)
        self.w_qph.setObjectName("w_qph")
        self.h_qph = QtWidgets.QHBoxLayout(self.w_qph)
        self.h_qph.setContentsMargins(-1, 0, -1, 0)
        self.h_qph.setObjectName("h_qph")
        self.qph_text = QtWidgets.QLabel(self.w_qph)
        self.qph_text.setObjectName("qph_text")
        self.h_qph.addWidget(self.qph_text)
        self.qph_data = QtWidgets.QLabel(self.w_qph)
        self.qph_data.setText("")
        self.qph_data.setObjectName("qph_data")
        self.h_qph.addWidget(self.qph_data)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.h_qph.addItem(spacerItem8)
        self.v_container.addWidget(self.w_qph)
        self.current_task_text = QtWidgets.QLabel(self.tab_1)
        self.current_task_text.setObjectName("current_task_text")
        self.v_container.addWidget(self.current_task_text)
        self.task_progress = QtWidgets.QProgressBar(self.tab_1)
        self.task_progress.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.task_progress.setAutoFillBackground(False)
        self.task_progress.setProperty("value", 24)
        self.task_progress.setTextVisible(True)
        self.task_progress.setInvertedAppearance(False)
        self.task_progress.setObjectName("task_progress")
        self.v_container.addWidget(self.task_progress)
        self.current_rb_text = QtWidgets.QLabel(self.tab_1)
        self.current_rb_text.setObjectName("current_rb_text")
        self.v_container.addWidget(self.current_rb_text)
        self.rebirth_progress = QtWidgets.QProgressBar(self.tab_1)
        self.rebirth_progress.setProperty("value", 24)
        self.rebirth_progress.setObjectName("rebirth_progress")
        self.v_container.addWidget(self.rebirth_progress)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.v_container.addItem(spacerItem9)
        self.verticalLayout_3.addLayout(self.v_container)
        self.tabWidget.addTab(self.tab_1, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.tab_3)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(self.tab_3)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.lifetime_itopod_kills_data = QtWidgets.QLabel(self.tab_3)
        self.lifetime_itopod_kills_data.setObjectName("lifetime_itopod_kills_data")
        self.horizontalLayout_3.addWidget(self.lifetime_itopod_kills_data)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem10)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_2 = QtWidgets.QLabel(self.tab_3)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_5.addWidget(self.label_2)
        self.lifetime_itopod_time_saved_data = QtWidgets.QLabel(self.tab_3)
        self.lifetime_itopod_time_saved_data.setObjectName("lifetime_itopod_time_saved_data")
        self.horizontalLayout_5.addWidget(self.lifetime_itopod_time_saved_data)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem11)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_3 = QtWidgets.QLabel(self.tab_3)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_6.addWidget(self.label_3)
        self.label_total_major_quests = QtWidgets.QLabel(self.tab_3)
        self.label_total_major_quests.setObjectName("label_total_major_quests")
        self.horizontalLayout_6.addWidget(self.label_total_major_quests)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem12)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_4 = QtWidgets.QLabel(self.tab_3)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_7.addWidget(self.label_4)
        self.label_total_minor_quests = QtWidgets.QLabel(self.tab_3)
        self.label_total_minor_quests.setObjectName("label_total_minor_quests")
        self.horizontalLayout_7.addWidget(self.label_total_minor_quests)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem13)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        spacerItem14 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem14)
        self.horizontalLayout_4.addLayout(self.verticalLayout_2)
        self.tabWidget.addTab(self.tab_3, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.run_button = QtWidgets.QPushButton(self.centralwidget)
        self.run_button.setObjectName("run_button")
        self.horizontalLayout.addWidget(self.run_button)
        self.stop_button = QtWidgets.QPushButton(self.centralwidget)
        self.stop_button.setEnabled(True)
        self.stop_button.setObjectName("stop_button")
        self.horizontalLayout.addWidget(self.stop_button)
        self.verticalLayout.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "NGU Script by Satyric", None, -1))
        self.combo_run.setItemText(0, QtWidgets.QApplication.translate("MainWindow", "Static Questing", None, -1))
        self.combo_run.setItemText(1, QtWidgets.QApplication.translate("MainWindow", "Static ITOPOD", None, -1))
        self.combo_run.setItemText(2, QtWidgets.QApplication.translate("MainWindow", "30 minute guffin run", None, -1))
        self.combo_run.setItemText(3, QtWidgets.QApplication.translate("MainWindow", "24 hour rebirth", None, -1))
        self.combo_run.setItemText(4, QtWidgets.QApplication.translate("MainWindow", "Speedrun", None, -1))
        self.run_options.setText(QtWidgets.QApplication.translate("MainWindow", "Options", None, -1))
        self.window_info_text.setText(QtWidgets.QApplication.translate("MainWindow", "Window not found!", None, -1))
        self.window_retry.setText(QtWidgets.QApplication.translate("MainWindow", "Retry", None, -1))
        self.elapsed_text.setText(QtWidgets.QApplication.translate("MainWindow", "Elapsed:", None, -1))
        self.exp_text.setText(QtWidgets.QApplication.translate("MainWindow", "EXP Gained:", None, -1))
        self.pp_text.setText(QtWidgets.QApplication.translate("MainWindow", "PP Gained:", None, -1))
        self.qp_text.setText(QtWidgets.QApplication.translate("MainWindow", "QP Gained:", None, -1))
        self.exph_text.setText(QtWidgets.QApplication.translate("MainWindow", "EXP/h:", None, -1))
        self.pph_text.setText(QtWidgets.QApplication.translate("MainWindow", "PP/h:", None, -1))
        self.qph_text.setText(QtWidgets.QApplication.translate("MainWindow", "QP/h:", None, -1))
        self.current_task_text.setText(QtWidgets.QApplication.translate("MainWindow", "Current Task", None, -1))
        self.current_rb_text.setText(QtWidgets.QApplication.translate("MainWindow", "Current Rebirth", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_1), QtWidgets.QApplication.translate("MainWindow", "General", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("MainWindow", "Total I.T.O.P.O.D snipes:", None, -1))
        self.lifetime_itopod_kills_data.setText(QtWidgets.QApplication.translate("MainWindow", "0", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("MainWindow", "Time saved:", None, -1))
        self.lifetime_itopod_time_saved_data.setText(QtWidgets.QApplication.translate("MainWindow", "0", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("MainWindow", "Total major quests:", None, -1))
        self.label_total_major_quests.setText(QtWidgets.QApplication.translate("MainWindow", "0", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("MainWindow", "Total minor quests:", None, -1))
        self.label_total_minor_quests.setText(QtWidgets.QApplication.translate("MainWindow", "0", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QtWidgets.QApplication.translate("MainWindow", "Statistics", None, -1))
        self.run_button.setText(QtWidgets.QApplication.translate("MainWindow", "Run", None, -1))
        self.stop_button.setText(QtWidgets.QApplication.translate("MainWindow", "Stop", None, -1))

