# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'inventory.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_InventorySelecter(object):
    def setupUi(self, InventorySelecter):
        InventorySelecter.setObjectName("InventorySelecter")
        InventorySelecter.resize(797, 358)
        self.centralwidget = QtWidgets.QWidget(InventorySelecter)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(2, 2, 2, 2)
        self.gridLayout.setObjectName("gridLayout")
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        self.label_18.setText("")
        self.label_18.setObjectName("label_18")
        self.gridLayout.addWidget(self.label_18, 5, 15, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.centralwidget)
        self.label_20.setText("")
        self.label_20.setObjectName("label_20")
        self.gridLayout.addWidget(self.label_20, 5, 17, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.centralwidget)
        self.label_22.setText("")
        self.label_22.setObjectName("label_22")
        self.gridLayout.addWidget(self.label_22, 5, 19, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setText("")
        self.label_16.setObjectName("label_16")
        self.gridLayout.addWidget(self.label_16, 5, 13, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setText("")
        self.label_17.setObjectName("label_17")
        self.gridLayout.addWidget(self.label_17, 5, 14, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setText("")
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 5, 11, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.centralwidget)
        self.label_21.setText("")
        self.label_21.setObjectName("label_21")
        self.gridLayout.addWidget(self.label_21, 5, 18, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setText("")
        self.label_15.setObjectName("label_15")
        self.gridLayout.addWidget(self.label_15, 5, 12, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setText("")
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 5, 10, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.centralwidget)
        self.label_19.setText("")
        self.label_19.setObjectName("label_19")
        self.gridLayout.addWidget(self.label_19, 5, 16, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.centralwidget)
        self.label_23.setText("")
        self.label_23.setObjectName("label_23")
        self.gridLayout.addWidget(self.label_23, 5, 20, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.centralwidget)
        self.label_30.setText("")
        self.label_30.setObjectName("label_30")
        self.gridLayout.addWidget(self.label_30, 6, 15, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.centralwidget)
        self.label_26.setText("")
        self.label_26.setObjectName("label_26")
        self.gridLayout.addWidget(self.label_26, 6, 11, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.centralwidget)
        self.label_24.setText("")
        self.label_24.setObjectName("label_24")
        self.gridLayout.addWidget(self.label_24, 5, 21, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.centralwidget)
        self.label_27.setText("")
        self.label_27.setObjectName("label_27")
        self.gridLayout.addWidget(self.label_27, 6, 12, 1, 1)
        self.label_31 = QtWidgets.QLabel(self.centralwidget)
        self.label_31.setText("")
        self.label_31.setObjectName("label_31")
        self.gridLayout.addWidget(self.label_31, 6, 16, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.centralwidget)
        self.label_28.setText("")
        self.label_28.setObjectName("label_28")
        self.gridLayout.addWidget(self.label_28, 6, 13, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.centralwidget)
        self.label_25.setText("")
        self.label_25.setObjectName("label_25")
        self.gridLayout.addWidget(self.label_25, 6, 10, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.centralwidget)
        self.label_29.setText("")
        self.label_29.setObjectName("label_29")
        self.gridLayout.addWidget(self.label_29, 6, 14, 1, 1)
        self.label_1 = QtWidgets.QLabel(self.centralwidget)
        self.label_1.setText("")
        self.label_1.setObjectName("label_1")
        self.gridLayout.addWidget(self.label_1, 4, 10, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 4, 17, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 4, 15, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 4, 11, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 4, 13, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 4, 14, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 4, 12, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setText("")
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 4, 19, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setText("")
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 4, 20, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setText("")
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 4, 18, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 4, 16, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setText("")
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 4, 21, 1, 1)
        self.label_34 = QtWidgets.QLabel(self.centralwidget)
        self.label_34.setText("")
        self.label_34.setObjectName("label_34")
        self.gridLayout.addWidget(self.label_34, 6, 19, 1, 1)
        self.label_36 = QtWidgets.QLabel(self.centralwidget)
        self.label_36.setText("")
        self.label_36.setObjectName("label_36")
        self.gridLayout.addWidget(self.label_36, 6, 21, 1, 1)
        self.label_32 = QtWidgets.QLabel(self.centralwidget)
        self.label_32.setText("")
        self.label_32.setObjectName("label_32")
        self.gridLayout.addWidget(self.label_32, 6, 17, 1, 1)
        self.label_38 = QtWidgets.QLabel(self.centralwidget)
        self.label_38.setText("")
        self.label_38.setObjectName("label_38")
        self.gridLayout.addWidget(self.label_38, 7, 11, 1, 1)
        self.label_33 = QtWidgets.QLabel(self.centralwidget)
        self.label_33.setText("")
        self.label_33.setObjectName("label_33")
        self.gridLayout.addWidget(self.label_33, 6, 18, 1, 1)
        self.label_41 = QtWidgets.QLabel(self.centralwidget)
        self.label_41.setText("")
        self.label_41.setObjectName("label_41")
        self.gridLayout.addWidget(self.label_41, 7, 14, 1, 1)
        self.label_39 = QtWidgets.QLabel(self.centralwidget)
        self.label_39.setText("")
        self.label_39.setObjectName("label_39")
        self.gridLayout.addWidget(self.label_39, 7, 12, 1, 1)
        self.label_42 = QtWidgets.QLabel(self.centralwidget)
        self.label_42.setText("")
        self.label_42.setObjectName("label_42")
        self.gridLayout.addWidget(self.label_42, 7, 15, 1, 1)
        self.label_35 = QtWidgets.QLabel(self.centralwidget)
        self.label_35.setText("")
        self.label_35.setObjectName("label_35")
        self.gridLayout.addWidget(self.label_35, 6, 20, 1, 1)
        self.label_40 = QtWidgets.QLabel(self.centralwidget)
        self.label_40.setText("")
        self.label_40.setObjectName("label_40")
        self.gridLayout.addWidget(self.label_40, 7, 13, 1, 1)
        self.label_37 = QtWidgets.QLabel(self.centralwidget)
        self.label_37.setText("")
        self.label_37.setObjectName("label_37")
        self.gridLayout.addWidget(self.label_37, 7, 10, 1, 1)
        self.label_43 = QtWidgets.QLabel(self.centralwidget)
        self.label_43.setText("")
        self.label_43.setObjectName("label_43")
        self.gridLayout.addWidget(self.label_43, 7, 16, 1, 1)
        self.label_45 = QtWidgets.QLabel(self.centralwidget)
        self.label_45.setText("")
        self.label_45.setObjectName("label_45")
        self.gridLayout.addWidget(self.label_45, 7, 18, 1, 1)
        self.label_47 = QtWidgets.QLabel(self.centralwidget)
        self.label_47.setText("")
        self.label_47.setObjectName("label_47")
        self.gridLayout.addWidget(self.label_47, 7, 20, 1, 1)
        self.label_44 = QtWidgets.QLabel(self.centralwidget)
        self.label_44.setText("")
        self.label_44.setObjectName("label_44")
        self.gridLayout.addWidget(self.label_44, 7, 17, 1, 1)
        self.label_46 = QtWidgets.QLabel(self.centralwidget)
        self.label_46.setText("")
        self.label_46.setObjectName("label_46")
        self.gridLayout.addWidget(self.label_46, 7, 19, 1, 1)
        self.label_48 = QtWidgets.QLabel(self.centralwidget)
        self.label_48.setText("")
        self.label_48.setObjectName("label_48")
        self.gridLayout.addWidget(self.label_48, 7, 21, 1, 1)
        self.label_49 = QtWidgets.QLabel(self.centralwidget)
        self.label_49.setText("")
        self.label_49.setObjectName("label_49")
        self.gridLayout.addWidget(self.label_49, 8, 10, 1, 1)
        self.label_50 = QtWidgets.QLabel(self.centralwidget)
        self.label_50.setText("")
        self.label_50.setObjectName("label_50")
        self.gridLayout.addWidget(self.label_50, 8, 11, 1, 1)
        self.label_51 = QtWidgets.QLabel(self.centralwidget)
        self.label_51.setText("")
        self.label_51.setObjectName("label_51")
        self.gridLayout.addWidget(self.label_51, 8, 12, 1, 1)
        self.label_52 = QtWidgets.QLabel(self.centralwidget)
        self.label_52.setText("")
        self.label_52.setObjectName("label_52")
        self.gridLayout.addWidget(self.label_52, 8, 13, 1, 1)
        self.label_53 = QtWidgets.QLabel(self.centralwidget)
        self.label_53.setText("")
        self.label_53.setObjectName("label_53")
        self.gridLayout.addWidget(self.label_53, 8, 14, 1, 1)
        self.label_54 = QtWidgets.QLabel(self.centralwidget)
        self.label_54.setText("")
        self.label_54.setObjectName("label_54")
        self.gridLayout.addWidget(self.label_54, 8, 15, 1, 1)
        self.label_55 = QtWidgets.QLabel(self.centralwidget)
        self.label_55.setText("")
        self.label_55.setObjectName("label_55")
        self.gridLayout.addWidget(self.label_55, 8, 16, 1, 1)
        self.label_56 = QtWidgets.QLabel(self.centralwidget)
        self.label_56.setText("")
        self.label_56.setObjectName("label_56")
        self.gridLayout.addWidget(self.label_56, 8, 17, 1, 1)
        self.label_57 = QtWidgets.QLabel(self.centralwidget)
        self.label_57.setText("")
        self.label_57.setObjectName("label_57")
        self.gridLayout.addWidget(self.label_57, 8, 18, 1, 1)
        self.label_58 = QtWidgets.QLabel(self.centralwidget)
        self.label_58.setText("")
        self.label_58.setObjectName("label_58")
        self.gridLayout.addWidget(self.label_58, 8, 19, 1, 1)
        self.label_59 = QtWidgets.QLabel(self.centralwidget)
        self.label_59.setText("")
        self.label_59.setObjectName("label_59")
        self.gridLayout.addWidget(self.label_59, 8, 20, 1, 1)
        self.label_60 = QtWidgets.QLabel(self.centralwidget)
        self.label_60.setText("")
        self.label_60.setObjectName("label_60")
        self.gridLayout.addWidget(self.label_60, 8, 21, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        InventorySelecter.setCentralWidget(self.centralwidget)

        self.retranslateUi(InventorySelecter)
        QtCore.QMetaObject.connectSlotsByName(InventorySelecter)

    def retranslateUi(self, InventorySelecter):
        _translate = QtCore.QCoreApplication.translate
        InventorySelecter.setWindowTitle(_translate("InventorySelecter", "Inventory selection"))

